FROM python:3.7
COPY . /src
WORKDIR /src
RUN pip install --no-cache-dir -U pip && rm -rf ~/.cache/pip
RUN pip install --no-cache-dir -r requirements.txt && rm -rf ~/.cache/pip

# Install Baidu SDK
RUN cd baidu_sdk && pip install .
# Install Spacy model
RUN python -m spacy download en_core_web_sm

# Install NewRelic
RUN pip install --no-cache-dir newrelic

EXPOSE 8000

CMD newrelic-admin run-program python demo.py
